### PR TITLE
update workflows

### PR DESCRIPTION
**Pull request by pawelru**
I'm going to trigger verdepcheck pipelines manually. You can check it's status here: https://github.com/insightsengineering/osprey/actions/workflows/scheduled.yaml?query=branch%3Afix_verdepcheck

### CODE REVIEW

**Comment by averissimo** [comment]
Updated versions and section on `DESCRIPTION`. 

Workflow is running, I'll be fixing it until badge is green or all fails are "expected"

Badge: [Scheduled 🕰️](https://github.com/insightsengineering/osprey/actions/workflows/scheduled.yaml)

**Comment by averissimo** [comment]
This line with `guide-box-bottom` added by #131 requires latest ggplot2 (3.5.0)

https://github.com/insightsengineering/osprey/blob/324fb2f5b1f245eace304d8974234574ee55888b/R/g_events_term_id.R#L314

**Comment by averissimo** [comment]
Sorry, for the lack of context.

The minimum strategies were failing as they need `gggplot2@3.5.0` since #131

My concrete question:
- Do you anticipate a problem by bumping `ggplot2` to version `3.5.0` from February 2024?
- Namely from environments where this package may be tested/deployed

**Comment by pawelru** [comment]
Ahh it's a pitty I haven't added this to my PR. Sorry about that.

If I recall correctly, `ggplot2` throws a bunch of lifecycle warnings that some functions have been softly deprecated and there are fully functional alternatives. Looking then into the PR it seems that it's about `aes_string()` and `size` argument of `geom_segment()`. An evidence in the bottom of my message. These were also present in our CI that automatically build testing environment with the newest version of CRAN packages.

---
```
r$> aes_string()
Aesthetic mapping: 
<empty>
Warning message:
`aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```

```
r$> geom_segment(size = 0.5)
geom_segment: arrow = NULL, arrow.fill = NULL, lineend = butt, linejoin = round, na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```

**Comment by pawelru** [comment]
It looks like all the verdepcheck pipelines are green - [last run](https://github.com/insightsengineering/osprey/actions/runs/8785715658). You have correctly bumped up ggplot dependency. This is not a problem anymore. Am I right on this?

**Comment by averissimo** [comment]
Yup! this one is ready to be merged as soon as CI workflow starts to works as expected

**Review by averissimo — APPROVED** [review]

**Pull request merged**
